services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: graphicdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - ./Backend/.env
    depends_on:
      - mysql

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

  nginx:
  build:
    context: .
    dockerfile: Dockerfile.nginx
  container_name: nginx
  restart: always
  ports:
    - "80:80"
  depends_on:
    - frontend
    - backend
