pipeline {
    agent any

    stages {

        stage('Create Environment File') {
            steps {
                dir('graphic-design-tool-main') {
                    sh '''
                    cat > Backend/.env <<EOF
DB_HOST=mysql
DB_USER=root
DB_PASSWORD=root123
DB_NAME=graphicdb
PORT=5050
EOF
                    '''
                }
            }
        }

        stage('Build Docker Containers') {
            steps {
                dir('graphic-design-tool-main') {
                    sh 'docker compose down'
                    sh 'docker compose up -d --build'
                }
            }
        }

        stage('Verify Running Containers') {
            steps {
                sh 'docker ps'
            }
        }

    }
}
